### ISSUE TITLE
Bad title causes issues with FFMPEG

### ISSUE THREAD

**Issue by tigsberg** [ihabunek/twitch-dl#112]
I'm using twitch-dl v2.0.1 and I keep getting an error when trying to download a Twitch VOD.
`
ffmpeg: error while loading shared libraries: libbz2.so.1.0: cannot open shared object file: No such file or directory`

I was confused what was causing the issue so I directly copied the FFMPEG input twitch-dl provides

`ffmpeg -i /tmp/twitch-dl/...`

and called it separately.

Apparently, the exclamation point and spaces in the title causes the issue. When removing it, FFMPEG stitches everything and produces a video - great!

Only issue is I am doing this via ssh on a different machine and want to automate it, so if there's a way to change the metadata of the VOD before beginning of the FFMPEG stitching process, I would be grateful.

**Comment by CDuncan** [comment]
Also having this issue. Trying to download a vod with "|" in the title causes the joining to fail. Stripping the title metadata and running the ffmpeg command manually is successful.

**Comment by Metalian0** [comment]
I also am experiencing the same issues with the datetime placeholder for --output. Datetime uses colens which can't be written to a filename in Windows.

**Comment by ihabunek** [comment]
This should be fixed since 2.7.0. Metadata is passed via a text file instead of command line arguments so special chars should no longer affect it. Please test and let me know.
