### ISSUE TITLE
[Feature Request] Download video chat

### ISSUE THREAD

**Issue by rogermiranda1000** [ihabunek/twitch-dl#116]
It would be awesome if you could download a JSON with the chat and the timestamp when it was sent

**Comment by garoto** [comment]
https://github.com/PetterKraabol/Twitch-Chat-Downloader

**Comment by rogermiranda1000** [comment]
That will do the trick. Still, having one unified tool for all this kind of things would be cool.

**Comment by ihabunek** [comment]
I might add this in the future.

**Comment by ihabunek** [comment]
@rogermiranda1000 @garoto Implemented since 2.7.0. Still experimental, I have some improvements in mind but it works pretty well. Check out the docs here: https://twitch-dl.bezdomni.net/commands/chat.html
