### ISSUE TITLE
[Feature request] Get creation date from video and put it into mkv

### ISSUE THREAD

**Issue by superbonaci** [ihabunek/twitch-dl#131]
In video feed can be seen the date from each video, when moving the mouse over each video. not sure if it's the creation time or last modification time, but would be great if such metadata could be added to the mkv:

https://www.twitch.tv/vlouue/videos?filter=all&sort=time

Can be read `Jan 12, 2022` when placing the mouse over:

![pic](https://github.com/ihabunek/twitch-dl/assets/8339596/b5c5e8f9-6fe3-493f-a301-de8736f8cff5)

**Comment by ihabunek** [comment]
Added in 2.8.1. Also added the `show` tag which I populated with the game name.
