### ISSUE TITLE
Feature request: Skip existing files

### ISSUE THREAD

**Issue by NuVanDibe** [ihabunek/twitch-dl#136]
Right now, if trying to download multiple videos by ID, and a file exists, it asks `File exists. Overwrite? [Y/n]:` and if you choose `n` then it aborts everything. It'd be nice if we had `yes once` `no once` `yes always` `no always` `abort` as options, as well as a `--skip-existing` flag to go along with the `--overwrite` flag.

**Comment by NuVanDibe** [comment]
For context, here's the command line I want to get working:

python twitch-dl.2.1.3.pyz download $(python twitch-dl.2.1.3.pyz videos streamername -c | grep -E '[0-9]+[0-9]+[0-9]+[0-9]+[0-9]+[0-9]' | sed 's/ .*//'  | tr '\n' ' ' | sed -e 's/\x1b\[[0-9;]*m//g') -q source

**Comment by NuVanDibe** [comment]
Addressed in PR #138

**Comment by ihabunek** [comment]
Released in 2.7.0.
