### ISSUE TITLE
python 3.12 compatibility

### ISSUE THREAD

**Issue by Datbug** [ihabunek/twitch-dl#137]
It doesn't seem to work with python 3.12.0, I call it from cmd and it does nothing

**Comment by ihabunek** [comment]
Can't reproduce, works for me with:

```
λ twitch-dl env
twitch-dl 2.1.3
Platform: Linux-6.4.15-200.fc38.x86_64-x86_64-with-glibc2.37
Python 3.12.0 (main, Oct  2 2023, 00:00:00) [GCC 13.2.1 20230728 (Red Hat 13.2.1-1)]
```

Can you paste result of `twitch-dl env` if that works. How did you install twitch-dl?

**Comment by Datbug** [comment]
I solved it, apparently it was a Windows configuration, sorry :)

![image](https://github.com/ihabunek/twitch-dl/assets/105828862/94726da3-4c82-49c7-b246-962d85c15124)

**Comment by ihabunek** [comment]
I love issues which solve themselves. :)
