### ISSUE TITLE
Downloading video, but only get audio file

### ISSUE THREAD

**Issue by naot97** [ihabunek/twitch-dl#150]
When I download a video by a command "twitch-dl download https://www.twitch.tv/videos/2093247333"

I only got a video file 102MB. When I played the video, it only had the audio with black screen.
My twitch-dl version is newest 2.1.4.
I tried with yt-dlp and it had both video and audio with 1.5GB. 
**The log:**

> Looking up video...
> Found: i cut the string to your future, to give you room for your destiny. by Will_Tha_Wise
> Output: 2024-03-17_2093247333_will_tha_wise_i_cut_the_string_to_your_future_to_give_you_room_for_your_destiny.mkv
> Fetching access token...
> Fetching playlists...
> 
> Available qualities:
> 1) 720p (1280x720)
> 2) audio_only
> Choose quality [default 1]: 1
> Fetching playlist...
> 
> Downloading 464 VODs using 5 workers to /tmp/twitch-dl/c9526b666beac0a38bfa_will_tha_wise_43836711739_1710657186/chunked
> Downloaded 463/464 VODs 99% of ~1.5GB at 10.4MB/s ETA 00:00     
> 
> Joining files...
> ffmpeg -i /tmp/twitch-dl/c9526b666beac0a38bfa_will_tha_wise_43836711739_1710657186/chunked/playlist_downloaded.m3u8 -c copy -metadata artist=Will_Tha_Wise -metadata title=i cut the string to your future, to give you room for your destiny. -metadata encoded_by=twitch-dl -stats -loglevel warning file:2024-03-17_2093247333_will_tha_wise_i_cut_the_string_to_your_future_to_give_you_room_for_your_destiny.mkv
> [in#0/hls @ 0x55b0bc8ebc40] New data stream with index 1 at pos:376 and DTS:74.274s
> [in#0/hls @ 0x55b0bc8ebc40] New video stream with index 2 at pos:57340 and DTS:76.666s
> size=  104268kB time=01:36:37.20 bitrate= 147.3kbits/s speed=1.82e+03x    
> 
> Deleting temporary files...
> 
> Downloaded: 2024-03-17_2093247333_will_tha_wise_i_cut_the_string_to_your_future_to_give_you_room_for_your_destiny.mkv
> 

**My package:**
python==3.8.10
m3u8==3.6.0
twitch-dl==2.1.4
ffmpeg-python==0.2.0
yt-dlp==2024.3.20.232704.dev0

**Comment by ihabunek** [comment]
My guess is that this is Twitch problem. Please reopen if it happens again so I can test. Thanks.
