### ISSUE TITLE
Twitch Enhanced Broadcast Streams

### ISSUE THREAD

**Issue by deanpcmad** [ihabunek/twitch-dl#154]
With the release of Twitch Enhanced Broadcast, downloading `source` downloads the `160p` version.

Checking the qualities, it appears the order is flipped so the worst quality is at the top. And checking the code, `source` looks at the first quality, which of course then downloads 160p in this instance.

| TEB stream (example ID 2115509448) | Normal stream (example ID 2129317291) |
|--------|--------|
| 1) 160p (284x160) | 1) 1080p60 (1920x1080) |
| 2) 360p (640x360) | 2) 720p60 (1280x720) |
| 3) 480p (852x480) | 3) 480p (852x480) |
| 4) 936p60 (1664x936) | 4) 360p (640x360) |
| 5) stream0 | 5) 160p (284x160) | 
| 6) audio_only | | 

Checking the playlist URLs, it appears that the best quality stream is always in the `chunked` directory. So maybe there should be an additional option called `best` or change `source` so it always downloads the chunked version?

**Comment by ihabunek** [comment]
@deanpcmad Thanks for reporting this. I've improvement playlist selection in 2.3.0, please test.

**Comment by deanpcmad** [comment]
Yes it looks like that's fixed. Thanks for sorting that so quickly!
