### ISSUE TITLE
(solved) pipx installation doesn't find module after version upgrade

### ISSUE THREAD

**Issue by Tofuraven** [ihabunek/twitch-dl#158]
(documentation purposes / a notice in case someone runs into the same problem)

After upgrading to the newest package version via pipx, upon executing any of the commands Python would immediately exit with a `ModuleNotFoundError` while looking for `twitchdl.console`
As the environment apparently didn't reflect the change of the main function moving to `twitchdl.cli` with an upgrade, a package reinstall was required to update the wrapper in pipx's bin directory.

**Comment by ihabunek** [comment]
Thanks!
