### ISSUE TITLE
GraphQL query failed

### ISSUE THREAD

**Issue by Neruay** [ihabunek/twitch-dl#159]
Trying to download a video using

`twitch-dl download --format mkv --quality 720p -o testvideo.mkv https://www.twitch.tv/videos/2159204723 --overwrite`

But getting error

`GraphQL query failed
* Argument "id" has invalid value 2159204723.
Expected type "ID", found 2159204723.`

It happens with random twitch videos - some of them randomly throwing this error, others are working fine

**Comment by ihabunek** [comment]
This has been fixed in the latest version 2.3.1, please upgrade.
