### ISSUE TITLE
TMP not working

### ISSUE THREAD

**Issue by superbonaci** [ihabunek/twitch-dl#164]
This command is not working in macOS:
https://twitch-dl.bezdomni.net/advanced.html

It always saves in `/var/folders/x9/g84bmm403x3_r6dx8twt92k50000gn/T/twitch-dl/`

**Comment by ihabunek** [comment]
I'm planning to move the tmp files to the [cache directory](https://github.com/ihabunek/twitch-dl/blob/170298ed6519a9e114487c2f7f40057cf168f217/twitchdl/cache.py#L44-L60). Already doing this when rendering [chat](https://twitch-dl.bezdomni.net/commands/chat.html).

Reasons:
* we want to keep the downloaded vods sometimes to allow aborting and then resuming downloads later
* seems like some OSs keep the temp files in memory (#105, #115)
* my fedora install has a temp partition limited to 15 gigs which is not enough for larger streams

**Comment by superbonaci** [comment]
Why not let choose custom directory?

**Comment by ihabunek** [comment]
Check out 2.9.0. It downloads to cache, but lets you override the cache location using the `--cache-dir` option.

**Comment by ihabunek** [comment]
Also there's `twitch-dl cache` to view cache usage and clear cached files.
