### ISSUE TITLE
[Question] Get notification about livestreams

### ISSUE THREAD

**Issue by bralbral** [ihabunek/twitch-dl#167]
Hello!

I have some thoughts about using this project to receive notifications about live broadcasts.

So I found [this](https://github.com/ihabunek/twitch-dl/blob/46c0314e4468d398ec8e9e02f895b39fdd7c7d96/twitchdl/twitch.py#L335) but it only returns completed streams or highlights.

Is the project suitable for this?

**Comment by ihabunek** [comment]
No, this project doesn't have that kind of feature. Sorry.
