### ISSUE TITLE
401 client error, unauthorized for URL

### ISSUE THREAD

**Issue by wolfgangam31** [ihabunek/twitch-dl#18]
I think that now that twitch needs oauth for all endpoints, this script does not work anymore, I'm getting the following error for command twitch-dl videos <user>

requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://api.twitch.tv/helix/users?login=...

**Comment by wolfgangam31** [comment]
I just tried it again from a different system, here is the full error: 

twitch-dl videos mizkif
Looking up user...
Traceback (most recent call last):
  File "/usr/local/bin/twitch-dl", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/twitchdl/console.py", line 154, in main
    args.func(**args.__dict__)
  File "/usr/local/lib/python3.7/dist-packages/twitchdl/commands.py", line 21, in videos
    user = twitch.get_user(channel_name)
  File "/usr/local/lib/python3.7/dist-packages/twitchdl/twitch.py", line 51, in get_user
    "login": login
  File "/usr/local/lib/python3.7/dist-packages/twitchdl/twitch.py", line 19, in authenticated_get
    response.raise_for_status()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://api.twitch.tv/helix/users?login=mizkif

**Comment by H-F-T** [comment]
Can confirm `twitch-dl videos` command broke for good this time. 
Waited couple days for it to maybe recover but this could be it. I think it already needed oauth token since I added mine in the script few months ago but probaly the end point changed and we need new endpoint or method to get videos list.

**Comment by wolfgangam31** [comment]
I think that there is a way to fix it, unfortunately I don't know how, but there are programs like twitch leecher that still works, so there must be a way.
I tried reading the source code of twitch-leecher but I'm not that good at c#....

**Comment by ihabunek** [comment]
They use the very unofficial graphql api, which twitch-dl uses for fetching clips. I'm inclined to fix it that way, but whatever I do you can expect it to break again in the future. :)

**Comment by ihabunek** [comment]
@wolfgangam31 @H-F-T Fixed in 1.8.0 (just released). Please test.

I went the grapql route, and also added the option to filter by game, e.g.:

```
twitch-dl videos --game "doom eternal" --game "cave story" bananasaurus_rex
```

**Comment by wolfgangam31** [comment]
> @wolfgangam31 @H-F-T Fixed in 1.8.0 (just released). Please test.
> 
> I went the grapql route, and also added the option to filter by game, e.g.:
> 
> ```
> twitch-dl videos --game "doom eternal" --game "cave story" bananasaurus_rex
> ```

thank you so much, I will get home in 3 hours, I'll test and report back. 
from what I understand, you expect twitch leecher to also break at some point with no way of fixing as twitch does not give an official option to download Vods?

**Comment by ihabunek** [comment]
Probably yes, IMO. We're all in the same boat. Wait and see.

**Comment by wolfgangam31** [comment]
Works gr8, thank you!
