### ISSUE TITLE
No installation instructions

### ISSUE THREAD

**Issue by jakebesworth** [ihabunek/twitch-dl#2]
Thanks so much for this awesome project!

There are no installation instructions and users might have to scour through the code, find errors, and search-engine a way to understanding. Code can't seem to easily be run natively, it **has** to be installed at a system-level.

**Comment by Juli4nDev** [comment]
The steps that I used to install the package were: `pip3 install twitch-dl`, This worked for me on Debian 10 with my normal user without sudo.

In the description there is also the ulr of the project in PyPi, there is also the command to do the installation :)
