### ISSUE TITLE
specify download quality in command line?

### ISSUE THREAD

**Issue by cjsjyh** [ihabunek/twitch-dl#22]
Is is possible to specify download quality in the commandl line?
ex) twitch-dl download --quality 480p http://url-to-video

**Comment by ihabunek** [comment]
Currently not, but I'll add it when I get the chance.

**Comment by Pelirrojo** [comment]
Hello,

I'm also interested in that feature, it can be very useful.

So far I've found this workaround:
```echo "1" | twitch-dl download VenomousTameWormHumbleLife```

From here:
[Stackoveflow: have-bash-script-answer-interactive-prompts](https://stackoverflow.com/a/3804645/1215781)

Hoping it'll help,
Manuel

**Comment by ihabunek** [comment]
Implemented in [1.10.0](https://github.com/ihabunek/twitch-dl/releases/tag/1.10.0)

Have fun.
