### ISSUE TITLE
Invalid Video

### ISSUE THREAD

**Issue by jap101** [ihabunek/twitch-dl#24]
i use this command alot to download clips:
e.g.
twitch-dl download https://www.twitch.tv/dracul1nx/clip/AbrasivePlayfulMangoMau5

but this gives an error like this:

Invalid video: https://www.twitch.tv/dracul1nx/clip/AbrasivePlayfulMangoMau5

this seems to only happen whenever there is a number in the 'slug'.

**Comment by ihabunek** [comment]
Fixed in [1.10.0](https://github.com/ihabunek/twitch-dl/releases/tag/1.10.0)

Thanks for reporting.
