### ISSUE TITLE
Error enumerating video qualities

### ISSUE THREAD

**Issue by SimplicityGuy** [ihabunek/twitch-dl#25]
When trying to download a video while the video was live, I got this error:
```python
Traceback (most recent call last):
  File "/usr/local/bin/twitch-dl", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/site-packages/twitchdl/console.py", line 168, in main
    args.func(args)
  File "/usr/local/lib/python3.8/site-packages/twitchdl/commands.py", line 171, in download
    return _download_video(video_id, args)
  File "/usr/local/lib/python3.8/site-packages/twitchdl/commands.py", line 226, in _download_video
    selected = _select_quality(parsed.playlists)
  File "/usr/local/lib/python3.8/site-packages/twitchdl/commands.py", line 81, in _select_quality
    resolution = "x".join(str(r) for r in p.stream_info.resolution)
TypeError: 'NoneType' object is not iterable
```

After the stream ended there is no issue with that same stream id.

**Comment by ihabunek** [comment]
Live streams are not supported. What would you expect to happen when downloading a live stream? Write it to a file as it's being broadcast starting with current time?

**Comment by SimplicityGuy** [comment]
This did work on another stream that was still live. I'd expect it to work in the way it did there -- download the VODs up to the current timestamp.

**Comment by ihabunek** [comment]
I've actually never tried this. :) I'll give it a go and see what can be done.

**Comment by SimplicityGuy** [comment]
FWIW, this broke between `1.9.0` and `1.10.0`.

**Comment by ihabunek** [comment]
Did it? 1.10 was released yesterday and you reported this 4 days ago.

BTW, i noticed a regression in 1.10 where downloading videos just by the ID will not work, it will think it's a clip, but downloading via full URL will work.

**Comment by SimplicityGuy** [comment]
True. Well, I tried a stream earlier, 1.10 didn't work, 1.9 did work. Last week when I reported it, I may have been on 1.8 when it worked, but I'm not sure. It could have been 1.9, but a particular stream didn't work.

**Comment by ihabunek** [comment]
This should work in `1.10.1` i did break it in `1.10.0` it seems. Please test.

**Comment by SimplicityGuy** [comment]
Great, thank you. I will give it a try this evening.

**Comment by SimplicityGuy** [comment]
Verified! `1.10.1` works great. Thank you @ihabunek!
