### ISSUE TITLE
Download ALL clips from channel?

### ISSUE THREAD

**Issue by capsload2** [ihabunek/twitch-dl#26]
Hey!

Can we download all clips from a channel?

**Comment by ihabunek** [comment]
This is currently not an option. I have some ideas for the future, keeping issue open.

**Comment by salmannotkhan** [comment]
I need more info regarding this packages usage in python program

**Comment by MegaSp00n** [comment]
+1 it would be good to be able to use in combination with an archive so I could periodically run a script to download all new videos from a channel

**Comment by Akshaykishore** [comment]
+1 on @MegaSp00n

**Comment by ihabunek** [comment]
Implemented in v.1.13.0. See https://github.com/ihabunek/twitch-dl#batch-downloading-clips

**Comment by capsload2** [comment]
Awesome!

Sometimes i get:

GraphQL query failed
* service timeout

Can we build a retry/timeout thing?
