### ISSUE TITLE
over-eager regex for clips prevents downloading video by id alone

### ISSUE THREAD

**Issue by lilywastaken** [ihabunek/twitch-dl#28]
yesterday's commit enabling numbers in clip slugs combined with clip regexes matching before video regexes means using a numeric video id will incorrectly try to download a clip resulting in a NoneError. it also means [this](https://github.com/ihabunek/twitch-dl/blob/8222df3670d21b4f822714a7655ee0bebb5cd5cf/twitchdl/commands.py#L166) regex will never match (since any valid matches will be consumed by the clip regex).

additionally, the other video regex requires `www` in the url, while omitting it is valid (it'll just redirect) and is what is [emitted by the `videos` command](https://github.com/ihabunek/twitch-dl/blob/f456d04de69d53fcd4c78ba9544d352c1519829e/twitchdl/output.py#L70). as a result copy-pasting either the output urls or ids will currently result in errors

**Comment by ihabunek** [comment]
@lilywastaken thanks for reporting, I was being too quick for my own good. Added some tests to cover this issue. Fixed in `1.10.1`
