### ISSUE TITLE
List videos without requiring Continue or Break

### ISSUE THREAD

**Issue by lodenrogue** [ihabunek/twitch-dl#30]
I'm trying to use this tool to automate some downloads. First I need to grab the video ids I'm interested in but videos command seems to require human input to get next set or to escape out of list. How can I list videos without requiring this manual input?

**Comment by ihabunek** [comment]
Implemented in [1.12.0](https://github.com/ihabunek/twitch-dl/releases/tag/1.12.0). Made paging off by default, activated by passing `--pager` option.
