### ISSUE TITLE
Add an alias for format #1 (source), so automation while parsing multiple URLs can be possible

### ISSUE THREAD

**Issue by garoto** [ihabunek/twitch-dl#33]
Different streamers will have VODs with different resolutions and framerates. The idea here is to alias the highest quality stream avaiable (#1 in twitch-dl and "source" in ~~yt-dl~~ streamlink lingo) with some keyword that can always be called within a script together with the new `--quality` option, e.g:

```
twitch-dl.exe download --start=00:17 --end=00:19 --max-workers 3 --quality source --format ts <URL>
```

**Comment by ihabunek** [comment]
Implemented in [1.12.0](https://github.com/ihabunek/twitch-dl/releases/tag/1.12.0).
