### ISSUE TITLE
Avoid using ffmpeg if possible

### ISSUE THREAD

**Issue by bennesp** [ihabunek/twitch-dl#36]
Thanks for your work. I would like to ask if it is possible to avoid using ffmpeg.

Files, at least for what I tried with videos, are in MPEG format. This means that doing something like
```
cat 1.ts 2.ts 3.ts ... > video.ts
```
already create a valid playable video (obviously in MPEG format).

Of course it cannot cover all the use cases, but for my use case it would be just perfect.

It would be brilliant if there could be the possibility to not use ffmpeg, for example, with a flag `--no-ffmpeg` or similar.

**Comment by bennesp** [comment]
Or maybe we could not use any flag, but simply don't use ffmpeg if format is set to "ts"

**Comment by ihabunek** [comment]
I could add something like a `--no-join` flag. Note that joining recently has been changed so that the whole playlist is passed to ffmpeg, to resolve some shenaningas done by twitch, see #35. When joining manually, joining would fail if twitch did this again.

As a matter of curiosity, why do you need this? Is ffmpeg unavailable, slower or something else?

**Comment by bennesp** [comment]
A `--no-join` would be great. Thanks for the advice on twitch big mess, I will definitely keep that in consideration.

The problem with ffmpeg for me is that I need to run `twitch-dl` in the context of a CI pipeline, with a docker image, and keeping docker images small is a big plus point. Installing ffmpeg requires, at least, more than 0.5GB of disk space (on a Ubuntu). Moreover, the CI will run on low-end resources, so I am trying to keep the processing minimum.

**Comment by garoto** [comment]
500MB is more than what some of my (cli-only) virtual Linux machines consume of HDD space.

**Comment by ihabunek** [comment]
Implemented in `v1.12.0`.
