### ISSUE TITLE
Add parameter to pass to parameters to ffmpeg

### ISSUE THREAD

**Issue by SimplicityGuy** [ihabunek/twitch-dl#37]
It would be nice to pass other args to ffmpeg. For instance, the ability to overwrite an existing file.

**Comment by ihabunek** [comment]
@SimplicityGuy I added an option for overwriting the target file in `1.12.0`. Is that fine or do you need this option for other things?

**Comment by SimplicityGuy** [comment]
@ihabunek this should be enough for now. Thanks for adding it!
