### ISSUE TITLE
Need downloadable cloudfront url alone for past broadcast video

### ISSUE THREAD

**Issue by Akshaykishore** [ihabunek/twitch-dl#41]
Hi ,

I was in need of getting the downloadable cloudfront url alone of past broadcast video ... Is that possible to get ?
Like this (https://d1mjs7qzzz669v.cloudfront.net/out/v1/16a8d8c636c0436db1576d475762881b/8062486b4cd947babfb3f96402358528/110c45e01aff48a7b809103f418b2fd4/index.m3u8)

**Comment by garoto** [comment]
Use `ffmpeg` for .m3u8 link.

**Comment by Akshaykishore** [comment]
Actually i have found out a way to get the m3u8 URL of live streaming video with node-twitch-get-stream.
Prerequisites:
npm install --save twitch-get-stream
 
Run the file above by passing the channel name (node m3u8.js)

```
 var twitchStreams = require('twitch-get-stream')

twitchStreams.get('amazonacademy4')
    .then(function(streams) {
        console.log(streams)
   });        
```
