### ISSUE TITLE
Support special unicode characters

### ISSUE THREAD

**Issue by TakacsDavid** [ihabunek/twitch-dl#46]
Hi! 
The other day I received an error by getting **the clips of the month** in version **twitch-dl.1.13.0.pyz**
```
Traceback (most recent call last):
  File "C:\Python\Python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python\Python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "twitch-dl.1.13.0.pyz\__main__.py", line 3, in <module>
  File "twitch-dl.1.13.0.pyz\twitchdl\console.py", line 223, in main
  File "twitch-dl.1.13.0.pyz\twitchdl\commands.py", line 88, in clips
  File "twitch-dl.1.13.0.pyz\twitchdl\output.py", line 94, in print_clip
  File "twitch-dl.1.13.0.pyz\twitchdl\output.py", line 52, in print_out
  File "C:\Python\Python38\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u0151' in position 78: character maps to <undefined>
```
Also, if the clip name contains special unicode characters it will display something like this:
Example: some text m▒▒▒asdasd
If its possible to support chars: "éáúőűí" ... etc would be nice.

Keep up the good work!

**Comment by ihabunek** [comment]
Could you give me a link to the clip so I can test?

**Comment by TakacsDavid** [comment]
Example for downloading: 
https://www.twitch.tv/hungarianrltournaments/clip/FunnyQuaintPastaAllenHuhu
Example for scanning clips: 
python twitch-dl.1.13.0.pyz clips magyarloltv --period all_time

Last one throws error: 
UnicodeEncodeError: 'charmap' codec can't encode character '\u0151' in position 28: character maps to <undefined>
But anyhow ▒▒▒ will be shown instead of proper characters (éáúőűí)

**Comment by ihabunek** [comment]
I cannot reproduce the issue with encoding. What's your OS and locale? On most linuxes you can run `locale` and get something like:

```
λ locale     
LANG=en_US.UTF-8
LANGUAGE=en_US:en
...
```

**Comment by TakacsDavid** [comment]
I'm currently using Windows 10
Git bash output:
```
$ locale
LANG=en_GB.UTF-8
LC_CTYPE="en_GB.UTF-8"
...
```
Here's what i see:
https://prnt.sc/voi73t
https://prnt.sc/voi7op

Pay attention on the green text. I also tried to parse the response message from your python to see if its only a console issue, but I couldn't see the the special characters neither this way.

**Comment by ihabunek** [comment]
Hm, your locale says UTF-8, but error says CP1250. Could you open python and run this and tell me what you get:
```
import sys
sys.getdefaultencoding()
```

**Comment by TakacsDavid** [comment]
https://prnt.sc/voit0u

**Comment by ihabunek** [comment]
Hm, that's as expected. I have a windows machine at home, I'll try to reproduce there later today.

**Comment by TakacsDavid** [comment]
OK, thank you for your time!

**Comment by ihabunek** [comment]
For the last screenshot, did you run python from the start menu or from git bash? I need you to run python from the same place from where you run twitch-dl.

**Comment by ihabunek** [comment]
Also, can you just try running the thing from cmd? That should work. You may need to disable color with --no-color.

**Comment by ihabunek** [comment]
OK, figured out a workaround, you can run this:
```
export PYTHONIOENCODING=UTF-8
```

and after that twitch-dl should work in git bash as well. You'll need to run it every time you start git bash or add it to .bashrc.

**Comment by TakacsDavid** [comment]
Great, I see! If I export utf-8 in git bash, it seems like its working! 
Thanks!
