### ISSUE TITLE
Listing *all* videos

### ISSUE THREAD

**Issue by drbyrd** [ihabunek/twitch-dl#49]
Is it possible to list all videos, not just the first 34?

syntax error using:

`twitch-dl videos bananasaurus_rex --period all_time
usage: twitch-dl [-h] [--version] {videos,clips,download} ...
twitch-dl: error: unrecognized arguments: --period all_time
`
Thanks

**Comment by florianperrotti** [comment]
same here

**Comment by ihabunek** [comment]
`--period` works only for listing clips. Videos by default shows first 10 which can be increased upto 100 by setting `--limit`, or viewed page by page by setting `--pager`.

**Comment by ihabunek** [comment]
Since 1.20.0 both clips and videos commands support `--all` to return all videos or clips even if it requires multiple requests to the server.
