### ISSUE TITLE
Certain portions of twitch vods

### ISSUE THREAD

**Issue by RichSteini** [ihabunek/twitch-dl#5]
Do you have any idea if it is possible to only download certain portions of twitch vods with python? If yes I would be very thankful if you could give me some tips!

**Comment by ihabunek** [comment]
I did plan to implement this at some point. Here's the way I would do it.

For example, looking at this video:
https://www.twitch.tv/videos/433571158

The video is 5:12:10 long which is 18.730 seconds.

Here is the m3u8 playlist for that video:
https://paste.sr.ht/~ihabunek/ed6f3a90065db5e10b52bb9c947df573de143345

The length of each VOD is specified in the playlist, the number after `#EXTINF` is the length in seconds. So each VOD in this playlist is 10 seconds long.

If we wanted to download the video partially, e.g. only from 1:00:00 to 1:30:00, we would need to skip the first 1h (3600 seconds), which is 360 VODs, and then download the following 30 minutes (1800 seconds) which is 180 VODs. Therfore, we'd need to download VODs from 360.ts upto 540.ts and join those to get our video slice.

Does this answer your question?

**Comment by ihabunek** [comment]
I took the time and implemented this in v.1.1.0.

Try adding `--start hh:mm` or `--end hh:mm` when downloading.

**Comment by RichSteini** [comment]
You are amazing, thank you very much !! :D

**Comment by ihabunek** [comment]
You're welcome. :)
