### ISSUE TITLE
[Feature Request] Get video details for URL

### ISSUE THREAD

**Issue by FiXato** [ihabunek/twitch-dl#51]
It would be nice if I could get the video details for a given URL, without directly downloading it.

For example:
`twitch-dl info https://www.twitch.tv/videos/857672197`

could return:
```
857672197
Let's Stream Death Road to Canada!
Kikoskia playing Death Road to Canada
Published 2021-01-01 @ 18:25:19  Length: 2 h 54 min
https://www.twitch.tv/videos/857672197
```

Ideally also including the target file name if I would actually download the video, and the available qualities.

(Though I can understand if you consider it outside the scope of the project.)

**Comment by FiXato** [comment]
Actually, never mind :) Noticed it was fairly simple to get the info I needed directly from the gql API with a couple of lines of bash. :)

**Comment by ihabunek** [comment]
I liked this idea so I implemented it in the [latest release](https://github.com/ihabunek/twitch-dl/releases/latest).
