### ISSUE TITLE
Error - This API does not exist   - when trying to download

### ISSUE THREAD

**Issue by wolfgangam31** [ihabunek/twitch-dl#53]
Hi,

Is this temporary or did twitch block it again?

Thanks

**Comment by ihabunek** [comment]
I'm guessing twitch blockage. Access token cannot be fetched. Need to investigate.

**Comment by ihabunek** [comment]
youtube-dl seems to have a fix already https://github.com/ytdl-org/youtube-dl/pull/27646

**Comment by ihabunek** [comment]
Fixed in the [latest release](https://github.com/ihabunek/twitch-dl/releases/latest).
