### ISSUE TITLE
Getting 'This API does not exist' when trying to download videos

### ISSUE THREAD

**Issue by scottyallen** [ihabunek/twitch-dl#55]
I'm seeing the following error when I try and download a video.  This just started happening in the past day or two.  Maybe there's been an api change on the twitch end?

$ twitch-dl download 875030866
Looking up video...
Found: Making an open source e-ink ebook reader - the Open Book! by StrangeParts
Fetching access token...
This API does not exist

**Comment by garoto** [comment]
Update to the latest release.

**Comment by scottyallen** [comment]
Yep, that did the trick. Sorry for not pulling first!
