### ISSUE TITLE
"New" slug/url pattern not being recognized as input

### ISSUE THREAD

**Issue by damianthtv** [ihabunek/twitch-dl#59]
Hello there! I'm having issues with the command console not recognizing the input for the following pattern clip info:

>  "slug": "NimbleBlindingHabaneroPeteZaroll-DVZP2IZXxT0py45u",
>             "url": "https://clips.twitch.tv/NimbleBlindingHabaneroPeteZaroll-DVZP2IZXxT0py45u",
>             "videoQualities": [
>                 {
>                     "frameRate": 60,
>                     "quality": "1080",
>                     "sourceURL": "https://production.assets.clips.twitchcdn.net/41066159324-offset-4856.mp4"
>                 },
>                 {
>                     "frameRate": 60,
>                     "quality": "720",
>                     "sourceURL": "https://production.assets.clips.twitchcdn.net/AT-cm%7C41066159324-offset-4856-720.mp4"
>                 },
>                 {
>                     "frameRate": 30,
>                     "quality": "480",
>                     "sourceURL": "https://production.assets.clips.twitchcdn.net/AT-cm%7C41066159324-offset-4856-480.mp4"
>                 },
>                 {
>                     "frameRate": 30,
>                     "quality": "360",
>                     "sourceURL": "https://production.assets.clips.twitchcdn.net/AT-cm%7C41066159324-offset-4856-360.mp4"
>                 }
>             ],

The error from twitch-dl is:

>  python .\twitch-dl.1.14.1.pyz download -q source --no-color NimbleBlindingHabaneroPeteZaroll-DVZP2IZXxT0py45u
> Invalid input: NimbleBlindingHabaneroPeteZaroll-DVZP2IZXxT0py45u

I tried with every sourceURL or URL string, and the same error happens.

I had several clips where these patterns appears, but it wasn't common before last week (I don't if its really a new pattern/twitchs update or not).

Looking at the code, I thought the reason why probably is the regex not matching. 

Best regards!

**Comment by ihabunek** [comment]
Fixed in 1.15.0
