### ISSUE TITLE
Other file formats?

### ISSUE THREAD

**Issue by EmptyCrown** [ihabunek/twitch-dl#6]
It seems that the downloaded files are in .mkv format? Any way to directly download as .mp4?

Great package btw.

**Comment by ihabunek** [comment]
Implemented in cbb0d6cfbd13ccb0b18e060d5786955f10534848.

Setting `--format=avi` will change the target file extension which is passed to ffmpeg, in turn producing the requested format/container. Tried `mp4` and `avi` and they work as expected.
