### ISSUE TITLE
Limit number of clips downloaded

### ISSUE THREAD

**Issue by gaspar-d** [ihabunek/twitch-dl#61]
Hi

There's any way to limit the number of clips downloaded in a batch?

In the options, I saw that using --period I can take some default values like last_day_ or last_week.

But if I want to download, last week but only 50 clips? 

It's possible to get only the 50 most viewed from last week?

**Comment by ihabunek** [comment]
This is possible since 1.20.0:

```
twitch-dl clips <channel> --download --period last_week --limit 50
```
