### ISSUE TITLE
Video download result in mp4? .mkv is not useable in final cut pro

### ISSUE THREAD

**Issue by ju-ius** [ihabunek/twitch-dl#63]
I've seen the video result is in the file format .mkv! is it possible to get it directly in an mp4?

Thanks for the answers

**Comment by ju-ius** [comment]
Im asking because if i want to convert the .mkv to an mp4 it will take a long time for a very long twitch stream. it would take me 10hrs or so to convert a 12 hr long video to mp4.

**Comment by garoto** [comment]
`twitch-dl download --format mp4 <VOD>`

For all the download options:

`twitch-dl download --help`
