### ISSUE TITLE
Is there any way to download to a specific timestamp only?

### ISSUE THREAD

**Issue by Cwickks** [ihabunek/twitch-dl#65]
Is there any way to download to a specific timestamp only? 
E.g., I would like to download from 00:00:00 to 00:00:30 only. It would round up to the nearest segment. For this example, The closest would be 00:00:37, which is the third segment. I think each segment composes of 12 seconds.

**Comment by ihabunek** [comment]
Yes: 

```
twitch-dl download 1031767825 --end 00:00:30
```

For all options see:

```
twitch-dl download --help
```
