### ISSUE TITLE
Change download output filename

### ISSUE THREAD

**Issue by deanpcmad** [ihabunek/twitch-dl#70]
Hey there, I found this project a few days ago and it's really going to help with one of my projects. Is there a way to change the output filename when downloading a video?

**Comment by garoto** [comment]
No. See: https://github.com/ihabunek/twitch-dl/blob/master/twitchdl/commands/download.py#L70-L81

**Comment by jtmoon79** [comment]
See https://github.com/ihabunek/twitch-dl/blob/4ff4c8763c79ce5a7468912fe9883b4592397652/README.md#overriding-file-name

However, `--output` appears to fail, see Issue #86

**Comment by ihabunek** [comment]
Released in [1.18.0](https://github.com/ihabunek/twitch-dl/releases/tag/1.18.0).
