### ISSUE TITLE
ETA is lying

### ISSUE THREAD

**Issue by CroquetteTheThe** [ihabunek/twitch-dl#75]
Scenario:
1/ You start the download of your stream
2/ You stop the script before it finishes the download
3/ You rerun the same command. The script uses what have been downloaded, to avoid redownloading the stream all over again.
Now, problem: when the script starts to get new data from twitch, it starts to display the speed and the ETA. The problem is that it is considering the old data like it has been downloaded in few seconds. The speed limit start to be wrong, and so is the ETA

**Comment by garoto** [comment]
WoW! Pretty much unusable.

**Comment by ihabunek** [comment]
Fixed in dd1f4e0d26d6cb14b7435ec62b18d183a3b37e17

**Comment by ihabunek** [comment]
Released in [1.17.0](https://github.com/ihabunek/twitch-dl/releases/tag/1.17.0).
