### ISSUE TITLE
Error when attempting to download a clip without a 'game' set

### ISSUE THREAD

**Issue by krisdahl** [ihabunek/twitch-dl#78]
> Looking up clip...
> Fetching access token...
> Traceback (most recent call last):
>   File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/runpy.py", line 193, in _run_module_as_main
>     return _run_code(code, main_globals, None,
>   File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/runpy.py", line 86, in _run_code
>     exec(code, run_globals)
>   File "./twitch-dl.1.16.1.pyz/__main__.py", line 3, in <module>
>   File "./twitch-dl.1.16.1.pyz/twitchdl/console.py", line 238, in main
>   File "./twitch-dl.1.16.1.pyz/twitchdl/commands/download.py", line 137, in download
>   File "./twitch-dl.1.16.1.pyz/twitchdl/commands/download.py", line 203, in _download_clip
> TypeError: 'NoneType' object is not subscriptable

It looks like issue is with the commands/download.py 

`print_out("Found: <green>{}</green> by <yellow>{}</yellow>, playing <blue>{}</blue> ({})".format(
        clip["title"],
        clip["broadcaster"]["displayName"],
        clip["game"]["name"],
        utils.format_duration(clip["durationSeconds"])
    ))`

I think just need to make sure game is set before referencing property of it.

**Comment by ihabunek** [comment]
Fixed in [1.18.1](https://github.com/ihabunek/twitch-dl/releases/tag/1.18.1).
