### ISSUE TITLE
Output argument for the output directory for the files

### ISSUE THREAD

**Issue by krisdahl** [ihabunek/twitch-dl#79]
It would be great if could be an argument that includes the directory and or the name/directory of the file.

eg

./twitch-dl.1.16.1.pyz download "foo" --quality=source /tmp/foo.mp4

./twitch-dl.1.16.1.pyz download "foo" --quality=source /tmp/

Thanks!

**Comment by gatesyp** [comment]
+1 for this!

**Comment by ihabunek** [comment]
Since 1.18.0 you can specify `--output /tmp/foo.mp4`. See [docs](https://github.com/ihabunek/twitch-dl#overriding-file-name) for more goodies.
