### ISSUE TITLE
VODs merging back together out of order 

### ISSUE THREAD

**Issue by CDittmeier** [ihabunek/twitch-dl#8]
Hello,

I was wondering if you could try to recreate the issue I am having using the following example. 

When running:

`twitch-dl download 464056346`

and passing input 1 for 720p

The temporary VODs seem to be merging together in the incorrect order so that the time is way out of sync towards the end of the video. 
So if you navigate to 05:09:00 to the downloaded file and 05:09:00 at the following url:

https://www.twitch.tv/videos/464056346

The video is not on the same frame (vastly different times
<img width="793" alt="Screen Shot 2019-08-13 at 2 15 23 PM" src="https://user-images.githubusercontent.com/24812731/62966436-0751dd00-bdd5-11e9-8ef0-06e8522d09e1.png">
<img width="1010" alt="Screen Shot 2019-08-13 at 2 17 52 PM" src="https://user-images.githubusercontent.com/24812731/62966526-36684e80-bdd5-11e9-9aff-b7f1d79d2d46.png">

). This has been the case for most VODs I have been downloading. I'm wondering if this is a universally issue or something I am experiencing locally. The temporary folder seems to be sorted correctly when I look at the temporary VODs numbered 1-2400. I use the stream times for an OCR application I maintain so the error has a huge impact for me (links people to the incorrect stream time).

Thank you!

**Comment by CDittmeier** [comment]
[
<img width="1275" alt="Screen Shot 2019-08-16 at 3 26 47 PM" src="https://user-images.githubusercontent.com/24812731/63193262-04f0bc80-c03b-11e9-994a-28a62f8b7fe8.png">
](url)

Likely related^

**Comment by CDittmeier** [comment]
As a heads up I am 99% sure what is breaking this is the red portion on the duration bar that is muted by Twitch:

https://www.twitch.tv/videos/464056346. The downloaded video skips the red portion

**Comment by ihabunek** [comment]
@CDittmeier I can reproduce this issue, and you're right that muted VODs are skipped.

The bug is that I'm expecting VODs to be named `1.ts`, `2.ts`, `3.ts`, ... And muted vods are named `1-muted.ts`. This bug also causes issues when downloading highlights.

Thanks for reporting and debugging, I'll push a fix.

**Comment by CDittmeier** [comment]
Also I'm now seeing http 410 errors on all requests. Maybe related to this?https://discuss.dev.twitch.tv/t/change-in-access-to-deprecated-kraken-twitch-apis/22241

**Comment by ihabunek** [comment]
Hm, strange, I'm not getting that at the moment. They might have reverted after the outlash.

Thanks about the info about the header, I'll add it.

The Twitch API is a mess, I could never really figure out what I should be using. Kraken has been deprecated when I started writing this app, but there was no way of doing these things in the [new api](https://dev.twitch.tv/docs/api/).

Looking at twitch.tv website itself, it still uses the same requests as twitch-dl to get the video data, access token and playlists. So I guess we should be OK for a while.

BTW, progress report about the muted videos: I added a fix to download them, but I'm getting ffmpeg errors when they're joined, not yet sure what's up.

**Comment by ihabunek** [comment]
@CDittmeier Adding the v5 header actually breaks the app for me, fetching videos returns:
```
{
    "error":"Bad Request","status":400,
    "message":"bananasaurus_rex Invalid Channel ID: channel ids must be in the form of an integer"
}
```
Which indicates that I'm probably still using v3 for this ^^;

**Comment by ihabunek** [comment]
If I add the v5 header, the channel ID must be given as a numeric ID, not a string. So now I need to do a second request to find the numeric ID before fetching videos. Sigh.

**Comment by CDittmeier** [comment]
Ah that's unfortunate. I've just been using the download piece which still works, but I see now that it does break the videos command.

Almost positive that the ffpmeg error is related to there being missing audio on the muted files. I think it doesn't know how to reconcile different durations, [which is why people have ended up padding silent clips with quite dummy audio files before joining them](https://stackoverflow.com/questions/46057412/ffmpeg-concat-multiple-videos-some-with-audio-some-without). Not sure the run time on padding the audio or if it would make sense to do in a loop through 1000s of mini VODs. 

I'm not quite sure how Twitch Leecher is dealing with it, but they somehow keep the timestamps straight on all the downloads. Might be worth digging into

**Comment by CDittmeier** [comment]
<img width="251" alt="Screen Shot 2019-08-22 at 11 55 35 AM" src="https://user-images.githubusercontent.com/24812731/63530128-dad44a00-c4d3-11e9-808d-bf3680c34514.png">

Looks like the muted VODs are being skipped over

**Comment by ihabunek** [comment]
@CDittmeier yeah, i haven't yet released the changes which fixes that, been busy. If you want to try it locally, change this line:
https://github.com/ihabunek/twitch-dl/blob/master/twitchdl/parse.py#L26

from:
```
    matches = re.findall(r"#EXTINF:(\d+)(\.\d+)?,.*?\s+(\d+.ts)", playlist)
```
to:
```
    matches = re.findall(r"#EXTINF:(\d+)(\.\d+)?,.*?\s+(.+)", playlist)
```

**Comment by CDittmeier** [comment]
Thoughts on adding to playlist URL: &allow_audio_only=true

**Comment by ihabunek** [comment]
@CDittmeier I put it in an issue #10 and will take a look after this mess. :)

TwitchLeecher had some problems with muted streams: https://github.com/Franiac/TwitchLeecher/issues/282

Also I notice that they first concatenate the vods, then feed them to ffmpeg:
https://github.com/Franiac/TwitchLeecher/blob/70e670f8fe8e703a12ef41ef076894146e09628f/TwitchLeecher/TwitchLeecher.Services/Services/TwitchService.cs#L767-L773

Both are implemented here:
https://github.com/Franiac/TwitchLeecher/blob/master/TwitchLeecher/TwitchLeecher.Services/Services/ProcessingService.cs

**Comment by ihabunek** [comment]
@CDittmeier Check out release 1.4.0. I changed the way playlists are parsed, so we should not have the problem with muted .ts files not being downloaded. I tried downloading the video you linked above and while ffmpeg is showing some errors when joining, the resulting video is fully playable.

If you add `--keep` option when downloading, the temp dir with all the VODs and the playlists as well will be preserved for debugging.

In the future, I will try to find out why the errors happen and how to fix them.

**Comment by CDittmeier** [comment]
Okay thanks! Still having issues with the timestamps but I appreciate the --keep functionality.

**Comment by lilywastaken** [comment]
> I tried downloading the video you linked above and while ffmpeg is showing some errors when joining, the resulting video is fully playable.

not sure if it's an issue on my end or something has changed in the past year since this issue was opened, but muted VODs are causing ffmpeg to crash resulting in an incomplete video for me. the concat-then-ffmpeg solution works fine but it's not very ergonomic (eg `cat *.vod > blahblah.ts && ffmpeg -err_detect ignore_err -i blahblah.ts -c copy blahblah-fixed.ts`)

**Comment by ihabunek** [comment]
@lilywastaken Reworked the merging logic recently. The m3u8 playlist itself  is given to ffmpeg as input instead of a list of files. Could you see how muted VODs are handled with version 1.11.0 or later?

**Comment by lilywastaken** [comment]
I tried a partially muted VOD just now, seems everything is rejoined properly and in order, without any crash. Thanks!
