### ISSUE TITLE
m3u8 requirement is out of date

### ISSUE THREAD

**Issue by ragibson** [ihabunek/twitch-dl#84]
Is this limit on the version of m3u8 still needed?
https://github.com/ihabunek/twitch-dl/blob/2f977be161492f153919f86c94f5df22719c39e5/setup.py#L32-L34
`m3u8<0.4` forces installation of a version that's at least ~2.5 years old and the package seems to work fine with version 1.0.0, released last week.

I'd think that this restriction could be dropped without issues, which would resolve some pip warnings when installing alongside other streaming packages. Regardless, allowing a more up-to-date version of this dependency would be a plus.

**Comment by ihabunek** [comment]
At the time of writing that code `0.3.12` was the latest version, and sub `1.0.0` releases tend to have breaking changes in minor versions, so it was to guard against that. No longer needed, I'll bump it to allow `1.*`.

**Comment by ihabunek** [comment]
Released in [1.17.1](https://github.com/ihabunek/twitch-dl/releases/tag/1.17.1).
