### ISSUE TITLE
Twitch-Dl unable to download audio files

### ISSUE THREAD

**Issue by cheesebellies** [ihabunek/twitch-dl#96]
When attempting to download VODs as audio files, it is unable to convert from m3u8 to mp3.
`twitch-dl download -w 50 --overwrite -q audio_only -o [location] [vod URI]`
Heres example output from the first 10 minutes of VOD.
`twitch-dl download -w 50 --overwrite -f mp3 -q audio_only -o ~/pytdl/vods/newvod.mp3 -e 00:10:00 1480683726`
result:
```
Looking up video...
Found: Time to get silly by moistcr1tikal
Output: /home/runner/pytdl/vods/newvod.mp3
Fetching access token...
Fetching playlists...
Fetching playlist...

Downloading 60 VODs using 50 workers to /tmp/twitch-dl/a5470d2cbc575496e127_moistcr1tikal_45383883564_1652234953/audio_only
Downloaded VOD 60/60 (100%) 14.3MB of ~14.3MB at 14.3MB/s                             

Joining files...
ffmpeg -i /tmp/twitch-dl/a5470d2cbc575496e127_moistcr1tikal_45383883564_1652234953/audio_only/playlist_downloaded.m3u8 -c copy -metadata artist=moistcr1tikal -metadata title=Time to get silly -metadata encoded_by=twitch-dl -stats -loglevel warning file:/home/runner/pytdl/vods/newvod.mp3 -y
[mp3 @ 0x56011ada71e0] Invalid audio stream. Exactly one MP3 audio stream is required.
Could not write header for output file #0 (incorrect codec parameters ?): Invalid argument

Joining files failed
```

trying to run the "joining files" command without metadata (previously downloaded files still in /tmp/twitch-dl/...):
`ffmpeg -i /tmp/twitch-dl/a5470d2cbc575496e127_moistcr1tikal_45383883564_1652234953/audio_only/playlist_downloaded.m3u8 -stats -loglevel warning file:/home/runner/pytdl/vods/newvod.mp3 -y
`result:
```
ffmpeg -i /tmp/twitch-dl/a5470d2cbc575496e127_moistcr1tikal_45383883564_1652234953/audio_only/playlist_downloaded.m3u8 -stats -loglevel warning file:/home/runner/pytdl/vods/newvod.mp3 -y
size=    9376kB time=00:10:00.03 bitrate= 128.0kbits/s speed=20.5x    
```
and it finishes without issues.

**Comment by ihabunek** [comment]
The problem is not with metadata, the problem is `-c copy` which tells ffmpeg to copy the input stream without reencoding. This is usually what we want but in your case you want to re-encode to mp3.

I don't think format conversion is something I want to add to twitch-dl so I suggest you download to 'mkv' then reencode to mp3, e.g.:

```
ffmpeg -i vod.mkv -b:a 192k vod.mp3
``

Alternatively, use `--no-join` to just download the vods, and join them yourself as you wish.

**Comment by cheesebellies** [comment]
Thank you for the feedback. I thought it automatically downloaded to mp3, rather than mkv... sorry for not looking into it further before posting this issue.
